name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  solidity-unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: cd solidity && yarn
      - name: Compile Contracts
        run: cd solidity && yes | npx hardhat compile
      - name: Run Tests
        run: cd solidity && npx hardhat test
